INSERT INTO users (
  username, email, password_hash, full_name, role, primary_sport, skill_level, city, bio, availability_notes
) VALUES
(
  'ananya_player',
  'ananya@sportsync.com',
  crypt('player123', gen_salt('bf')),
  'Ananya Rao',
  'player',
  'Badminton',
  'Intermediate',
  'Hyderabad',
  'Weekend badminton player looking for coached sessions and doubles groups.',
  'Available weekdays after 6 PM and weekends.'
),
(
  'rahul_player',
  'rahul@sportsync.com',
  crypt('player123', gen_salt('bf')),
  'Rahul Menon',
  'player',
  'Tennis',
  'Beginner',
  'Hyderabad',
  'Learning tennis and looking for friendly practice groups.',
  'Usually free on Saturday mornings.'
),
(
  'isha_player',
  'isha@sportsync.com',
  crypt('player123', gen_salt('bf')),
  'Isha Kulkarni',
  'player',
  'Badminton',
  'Beginner',
  'Hyderabad',
  'New to badminton and excited to join weekday coaching sessions.',
  'Mostly available on weekday evenings.'
),
(
  'vikram_player',
  'vikram@sportsync.com',
  crypt('player123', gen_salt('bf')),
  'Vikram Desai',
  'player',
  'Tennis',
  'Intermediate',
  'Hyderabad',
  'Looking for competitive rallies and structured tennis practice.',
  'Prefers early morning sessions and weekend drills.'
),
(
  'priya_player',
  'priya@sportsync.com',
  crypt('player123', gen_salt('bf')),
  'Priya Shah',
  'player',
  'Badminton',
  'Advanced',
  'Hyderabad',
  'Club-level badminton player searching for strong sparring partners.',
  'Usually free after 7 PM on weekdays.'
),
(
  'neha_player',
  'neha@sportsync.com',
  crypt('player123', gen_salt('bf')),
  'Neha Joshi',
  'player',
  'Badminton',
  'Intermediate',
  'Hyderabad',
  'Enjoys weekday badminton games and mixed doubles sessions.',
  'Available Tuesday and Thursday evenings.'
),
(
  'arav_player',
  'arav@sportsync.com',
  crypt('player123', gen_salt('bf')),
  'Arav Bansal',
  'player',
  'Tennis',
  'Beginner',
  'Hyderabad',
  'Looking for regular tennis coaching and easy matchplay sessions.',
  'Free on weekday mornings and Sunday evenings.'
),
(
  'kavya_player',
  'kavya@sportsync.com',
  crypt('player123', gen_salt('bf')),
  'Kavya Ramesh',
  'player',
  'Badminton',
  'Beginner',
  'Hyderabad',
  'Recently started playing badminton and wants coaching plus group games.',
  'Usually free after office hours and on Saturdays.'
),
(
  'coach_meera',
  'meera@sportsync.com',
  crypt('coach123', gen_salt('bf')),
  'Meera Nair',
  'coach',
  'Badminton',
  'Advanced',
  'Hyderabad',
  'Certified badminton coach focused on footwork, conditioning, and match prep.',
  'Takes evening and weekend slots.'
),
(
  'coach_arjun',
  'arjun@sportsync.com',
  crypt('coach123', gen_salt('bf')),
  'Arjun Varma',
  'coach',
  'Tennis',
  'Advanced',
  'Hyderabad',
  'Former district player offering technical and tactical tennis coaching.',
  'Open for morning coaching blocks.'
),
(
  'coach_nisha',
  'nisha@sportsync.com',
  crypt('coach123', gen_salt('bf')),
  'Nisha Kapoor',
  'coach',
  'Badminton',
  'Advanced',
  'Hyderabad',
  'Badminton coach focused on beginners, doubles movement, and consistency drills.',
  'Usually available for morning and evening sessions.'
),
(
  'coach_adi',
  'adi@sportsync.com',
  crypt('coach123', gen_salt('bf')),
  'Aditya Rao',
  'coach',
  'Tennis',
  'Advanced',
  'Hyderabad',
  'Tennis coach for beginner and intermediate players with an emphasis on footwork and rally control.',
  'Takes both weekday and weekend sessions.'
),
(
  'coach_saanvi',
  'saanvi@sportsync.com',
  crypt('coach123', gen_salt('bf')),
  'Saanvi Gupta',
  'coach',
  'Badminton',
  'Advanced',
  'Hyderabad',
  'Badminton coach focused on singles endurance, court coverage, and match temperament.',
  'Open for weekday mornings and weekend evenings.'
),
(
  'coach_rohan',
  'rohan@sportsync.com',
  crypt('coach123', gen_salt('bf')),
  'Rohan Malhotra',
  'coach',
  'Tennis',
  'Advanced',
  'Hyderabad',
  'Tennis coach who works on stroke mechanics, serve rhythm, and point construction.',
  'Available for morning and post-work sessions.'
),
(
  'coach_tara',
  'tara@sportsync.com',
  crypt('coach123', gen_salt('bf')),
  'Tara Bedi',
  'coach',
  'Badminton',
  'Advanced',
  'Hyderabad',
  'Badminton coach who specializes in beginner foundations, net play, and movement recovery.',
  'Usually open for weekday evenings and Sunday mornings.'
),
(
  'coach_dev',
  'dev@sportsync.com',
  crypt('coach123', gen_salt('bf')),
  'Dev Khanna',
  'coach',
  'Tennis',
  'Advanced',
  'Hyderabad',
  'Tennis coach with a focus on footwork, serve consistency, and rally discipline.',
  'Available across weekday mornings and weekend slots.'
),
(
  'owner_sneha',
  'sneha@sportsync.com',
  crypt('owner123', gen_salt('bf')),
  'Sneha Reddy',
  'owner',
  'Badminton',
  'Advanced',
  'Hyderabad',
  'Runs a multi-sport indoor facility in Gachibowli.',
  'Facility helpdesk available 8 AM to 9 PM.'
),
(
  'owner_karthik',
  'karthik@sportsync.com',
  crypt('owner123', gen_salt('bf')),
  'Karthik Iyer',
  'owner',
  'Tennis',
  'Advanced',
  'Hyderabad',
  'Owns an outdoor tennis center used by college players and coaches.',
  'Open to recurring bookings.'
),
(
  'owner_farah',
  'farah@sportsync.com',
  crypt('owner123', gen_salt('bf')),
  'Farah Khan',
  'owner',
  'Badminton',
  'Advanced',
  'Hyderabad',
  'Manages an indoor sports hub with both badminton and tennis facilities.',
  'Venue desk active from 7 AM to 10 PM.'
),
(
  'owner_manoj',
  'manoj@sportsync.com',
  crypt('owner123', gen_salt('bf')),
  'Manoj Kulkarni',
  'owner',
  'Tennis',
  'Advanced',
  'Hyderabad',
  'Operates a neighborhood racket sports venue with steady weekday traffic.',
  'Front desk open every day from 6 AM to 9 PM.'
);

INSERT INTO coach_profiles (user_id, experience_years, hourly_rate, coaching_history) VALUES
((SELECT id FROM users WHERE username = 'coach_meera'), 7, 900.00, 'Worked with school and academy level badminton players for 7 years.'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 9, 1200.00, 'Former district circuit competitor with structured beginner-to-advanced programs.'),
((SELECT id FROM users WHERE username = 'coach_nisha'), 5, 750.00, 'Runs structured badminton sessions for new and returning players.'),
((SELECT id FROM users WHERE username = 'coach_adi'), 6, 950.00, 'Coached tennis learners through stroke building and match play basics.'),
((SELECT id FROM users WHERE username = 'coach_saanvi'), 8, 1100.00, 'Guided academy and club players through singles conditioning and tournament preparation.'),
((SELECT id FROM users WHERE username = 'coach_rohan'), 7, 1050.00, 'Works with recreational and intermediate tennis players on shot consistency and tactical play.'),
((SELECT id FROM users WHERE username = 'coach_tara'), 4, 700.00, 'Runs beginner-friendly badminton sessions with strong emphasis on consistency and court movement.'),
((SELECT id FROM users WHERE username = 'coach_dev'), 8, 1150.00, 'Trains club-level tennis players through tactical drills, serve repetition, and match preparation.');

INSERT INTO coach_availability (coach_id, weekday, start_time, end_time) VALUES
((SELECT id FROM users WHERE username = 'coach_meera'), 0, '07:00', '10:00'),
((SELECT id FROM users WHERE username = 'coach_meera'), 0, '17:00', '20:00'),
((SELECT id FROM users WHERE username = 'coach_meera'), 1, '06:30', '09:30'),
((SELECT id FROM users WHERE username = 'coach_meera'), 1, '18:00', '21:00'),
((SELECT id FROM users WHERE username = 'coach_meera'), 2, '06:30', '09:30'),
((SELECT id FROM users WHERE username = 'coach_meera'), 2, '17:00', '20:00'),
((SELECT id FROM users WHERE username = 'coach_meera'), 3, '06:30', '09:30'),
((SELECT id FROM users WHERE username = 'coach_meera'), 3, '18:00', '21:00'),
((SELECT id FROM users WHERE username = 'coach_meera'), 4, '06:30', '09:30'),
((SELECT id FROM users WHERE username = 'coach_meera'), 4, '17:30', '20:30'),
((SELECT id FROM users WHERE username = 'coach_meera'), 5, '06:30', '09:30'),
((SELECT id FROM users WHERE username = 'coach_meera'), 5, '18:00', '21:00'),
((SELECT id FROM users WHERE username = 'coach_meera'), 6, '08:00', '12:00'),
((SELECT id FROM users WHERE username = 'coach_meera'), 6, '16:00', '19:00'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 0, '07:00', '10:00'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 0, '16:00', '19:00'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 1, '06:00', '09:00'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 1, '17:00', '20:00'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 2, '06:00', '10:00'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 2, '17:00', '20:00'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 3, '06:30', '09:30'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 3, '17:00', '20:00'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 4, '06:00', '10:00'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 4, '17:00', '20:00'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 5, '06:00', '09:00'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 5, '16:30', '19:30'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 6, '07:00', '11:00'),
((SELECT id FROM users WHERE username = 'coach_arjun'), 6, '16:00', '19:00'),
((SELECT id FROM users WHERE username = 'coach_nisha'), 0, '08:00', '11:00'),
((SELECT id FROM users WHERE username = 'coach_nisha'), 1, '07:00', '10:00'),
((SELECT id FROM users WHERE username = 'coach_nisha'), 2, '18:00', '21:00'),
((SELECT id FROM users WHERE username = 'coach_nisha'), 3, '07:00', '10:00'),
((SELECT id FROM users WHERE username = 'coach_nisha'), 4, '18:00', '21:00'),
((SELECT id FROM users WHERE username = 'coach_nisha'), 5, '07:00', '10:00'),
((SELECT id FROM users WHERE username = 'coach_nisha'), 6, '08:00', '12:00'),
((SELECT id FROM users WHERE username = 'coach_adi'), 0, '07:00', '10:00'),
((SELECT id FROM users WHERE username = 'coach_adi'), 1, '06:00', '09:00'),
((SELECT id FROM users WHERE username = 'coach_adi'), 2, '17:00', '20:00'),
((SELECT id FROM users WHERE username = 'coach_adi'), 3, '06:00', '09:00'),
((SELECT id FROM users WHERE username = 'coach_adi'), 4, '17:00', '20:00'),
((SELECT id FROM users WHERE username = 'coach_adi'), 5, '06:00', '09:00'),
((SELECT id FROM users WHERE username = 'coach_adi'), 6, '07:00', '11:00'),
((SELECT id FROM users WHERE username = 'coach_saanvi'), 1, '07:00', '10:00'),
((SELECT id FROM users WHERE username = 'coach_saanvi'), 2, '07:00', '10:00'),
((SELECT id FROM users WHERE username = 'coach_saanvi'), 4, '18:00', '21:00'),
((SELECT id FROM users WHERE username = 'coach_saanvi'), 6, '16:00', '20:00'),
((SELECT id FROM users WHERE username = 'coach_rohan'), 0, '06:30', '09:30'),
((SELECT id FROM users WHERE username = 'coach_rohan'), 2, '18:00', '21:00'),
((SELECT id FROM users WHERE username = 'coach_rohan'), 3, '06:30', '09:30'),
((SELECT id FROM users WHERE username = 'coach_rohan'), 5, '17:00', '20:00'),
((SELECT id FROM users WHERE username = 'coach_rohan'), 6, '07:00', '11:00'),
((SELECT id FROM users WHERE username = 'coach_tara'), 1, '18:00', '21:00'),
((SELECT id FROM users WHERE username = 'coach_tara'), 3, '18:00', '21:00'),
((SELECT id FROM users WHERE username = 'coach_tara'), 5, '17:30', '20:30'),
((SELECT id FROM users WHERE username = 'coach_tara'), 6, '08:00', '11:00'),
((SELECT id FROM users WHERE username = 'coach_dev'), 1, '06:00', '09:00'),
((SELECT id FROM users WHERE username = 'coach_dev'), 2, '06:00', '09:00'),
((SELECT id FROM users WHERE username = 'coach_dev'), 4, '17:00', '20:00'),
((SELECT id FROM users WHERE username = 'coach_dev'), 6, '07:00', '10:00');

INSERT INTO courts (owner_id, name, sport_type, location, surface, price_per_hour, capacity, description) VALUES
(
  (SELECT id FROM users WHERE username = 'owner_sneha'),
  'Gachibowli Smash Arena Court 1',
  'Badminton',
  'Gachibowli, Hyderabad',
  'Synthetic',
  500.00,
  4,
  'Indoor air-conditioned badminton court with lighting and equipment rental.'
),
(
  (SELECT id FROM users WHERE username = 'owner_sneha'),
  'Gachibowli Smash Arena Court 2',
  'Badminton',
  'Gachibowli, Hyderabad',
  'Synthetic',
  450.00,
  4,
  'Practice-focused court ideal for group sessions and drills.'
),
(
  (SELECT id FROM users WHERE username = 'owner_karthik'),
  'Sunrise Tennis Centre Court A',
  'Tennis',
  'Madhapur, Hyderabad',
  'Hard',
  700.00,
  4,
  'Outdoor hard-court tennis space with floodlights for early and late sessions.'
),
(
  (SELECT id FROM users WHERE username = 'owner_sneha'),
  'lake side court',
  'Badminton',
  'Hyderabad',
  'Synthetic',
  500.00,
  8,
  'Larger badminton court setup that works well for rallies, drills, and demo bookings.'
),
(
  (SELECT id FROM users WHERE username = 'owner_karthik'),
  'Sunrise Tennis Centre Court B',
  'Tennis',
  'Madhapur, Hyderabad',
  'Hard',
  750.00,
  4,
  'Second outdoor tennis court with similar lighting and coaching-friendly timing.'
),
(
  (SELECT id FROM users WHERE username = 'owner_farah'),
  'Jubilee Hills Shuttle Court 1',
  'Badminton',
  'Jubilee Hills, Hyderabad',
  'Wooden',
  650.00,
  4,
  'Premium indoor badminton court with bright lighting and cushioned wooden flooring.'
),
(
  (SELECT id FROM users WHERE username = 'owner_farah'),
  'Jubilee Hills Shuttle Court 2',
  'Badminton',
  'Jubilee Hills, Hyderabad',
  'Wooden',
  600.00,
  4,
  'Training-friendly badminton court suited for drills, sparring, and evening games.'
),
(
  (SELECT id FROM users WHERE username = 'owner_farah'),
  'Hitech Tennis Studio Court 1',
  'Tennis',
  'Hitech City, Hyderabad',
  'Clay',
  850.00,
  4,
  'Well-maintained clay tennis court designed for coaching and long rally sessions.'
),
(
  (SELECT id FROM users WHERE username = 'owner_manoj'),
  'Banjara Rally Court',
  'Badminton',
  'Banjara Hills, Hyderabad',
  'Synthetic',
  550.00,
  4,
  'Neighborhood badminton court popular for quick weekday games and practice rallies.'
),
(
  (SELECT id FROM users WHERE username = 'owner_manoj'),
  'Banjara Tennis Court',
  'Tennis',
  'Banjara Hills, Hyderabad',
  'Hard',
  780.00,
  4,
  'Outdoor tennis court with bright evening lights and coaching-friendly timing.'
);

INSERT INTO court_availability (court_id, weekday, start_time, end_time) VALUES
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 0, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 0, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 1, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 1, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 2, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 2, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 3, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 3, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 4, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 4, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 5, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 5, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 6, '06:00', '13:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'), 6, '15:00', '21:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 0, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 0, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 1, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 1, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 2, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 2, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 3, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 3, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 4, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 4, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 5, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 5, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 6, '06:00', '13:00'),
((SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'), 6, '15:00', '21:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 0, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 0, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 1, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 1, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 2, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 2, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 3, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 3, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 4, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 4, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 5, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 5, '16:00', '22:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 6, '06:00', '13:00'),
((SELECT id FROM courts WHERE name = 'lake side court'), 6, '15:00', '21:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 0, '06:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 0, '16:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 1, '06:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 1, '16:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 2, '06:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 2, '16:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 3, '06:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 3, '16:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 4, '06:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 4, '16:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 5, '06:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 5, '16:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 6, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'), 6, '15:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 0, '06:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 0, '16:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 1, '06:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 1, '16:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 2, '06:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 2, '16:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 3, '06:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 3, '16:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 4, '06:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 4, '16:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 5, '06:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 5, '16:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 6, '06:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court B'), 6, '15:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 1'), 0, '07:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 1'), 0, '17:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 1'), 2, '07:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 1'), 2, '17:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 1'), 4, '07:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 1'), 4, '17:00', '22:00'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 1'), 6, '08:00', '21:00'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 2'), 1, '06:30', '11:30'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 2'), 1, '17:00', '21:30'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 2'), 3, '06:30', '11:30'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 2'), 3, '17:00', '21:30'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 2'), 5, '06:30', '11:30'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 2'), 5, '17:00', '21:30'),
((SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 2'), 6, '08:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Hitech Tennis Studio Court 1'), 0, '06:00', '10:00'),
((SELECT id FROM courts WHERE name = 'Hitech Tennis Studio Court 1'), 1, '06:00', '10:00'),
((SELECT id FROM courts WHERE name = 'Hitech Tennis Studio Court 1'), 1, '17:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Hitech Tennis Studio Court 1'), 3, '06:00', '10:00'),
((SELECT id FROM courts WHERE name = 'Hitech Tennis Studio Court 1'), 3, '17:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Hitech Tennis Studio Court 1'), 5, '06:00', '10:00'),
((SELECT id FROM courts WHERE name = 'Hitech Tennis Studio Court 1'), 6, '07:00', '12:00'),
((SELECT id FROM courts WHERE name = 'Banjara Rally Court'), 1, '07:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Banjara Rally Court'), 1, '17:00', '21:00'),
((SELECT id FROM courts WHERE name = 'Banjara Rally Court'), 3, '07:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Banjara Rally Court'), 3, '17:00', '21:00'),
((SELECT id FROM courts WHERE name = 'Banjara Rally Court'), 5, '07:00', '11:00'),
((SELECT id FROM courts WHERE name = 'Banjara Rally Court'), 5, '17:00', '21:00'),
((SELECT id FROM courts WHERE name = 'Banjara Rally Court'), 6, '08:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Banjara Tennis Court'), 0, '06:00', '10:00'),
((SELECT id FROM courts WHERE name = 'Banjara Tennis Court'), 2, '06:00', '10:00'),
((SELECT id FROM courts WHERE name = 'Banjara Tennis Court'), 2, '17:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Banjara Tennis Court'), 4, '06:00', '10:00'),
((SELECT id FROM courts WHERE name = 'Banjara Tennis Court'), 4, '17:00', '20:00'),
((SELECT id FROM courts WHERE name = 'Banjara Tennis Court'), 6, '07:00', '11:00');

INSERT INTO bookings (
  player_id, court_id, coach_id, booking_date, start_time, end_time, total_price, notes
) VALUES
(
  (SELECT id FROM users WHERE username = 'ananya_player'),
  (SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'),
  (SELECT id FROM users WHERE username = 'coach_meera'),
  DATE '2026-04-08',
  '18:00',
  '19:00',
  1400.00,
  'Focused coaching session for doubles rotation and net play.'
),
(
  (SELECT id FROM users WHERE username = 'rahul_player'),
  (SELECT id FROM courts WHERE name = 'Sunrise Tennis Centre Court A'),
  (SELECT id FROM users WHERE username = 'coach_arjun'),
  DATE '2026-04-09',
  '07:00',
  '08:00',
  1900.00,
  'Beginner tennis fundamentals session.'
),
(
  (SELECT id FROM users WHERE username = 'isha_player'),
  (SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 2'),
  (SELECT id FROM users WHERE username = 'coach_saanvi'),
  DATE '2026-04-11',
  '17:00',
  '18:00',
  1700.00,
  'Intro coaching session focused on grip, movement, and basic clears.'
),
(
  (SELECT id FROM users WHERE username = 'vikram_player'),
  (SELECT id FROM courts WHERE name = 'Hitech Tennis Studio Court 1'),
  (SELECT id FROM users WHERE username = 'coach_rohan'),
  DATE '2026-04-12',
  '07:00',
  '08:00',
  1900.00,
  'Intermediate tennis session with serve rhythm and rally drills.'
),
(
  (SELECT id FROM users WHERE username = 'priya_player'),
  (SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 1'),
  NULL,
  DATE '2026-04-13',
  '19:00',
  '20:00',
  650.00,
  'Court-only booking for match practice with friends.'
),
(
  (SELECT id FROM users WHERE username = 'neha_player'),
  (SELECT id FROM courts WHERE name = 'Banjara Rally Court'),
  (SELECT id FROM users WHERE username = 'coach_tara'),
  DATE '2026-04-14',
  '18:00',
  '19:00',
  1250.00,
  'Weekday badminton coaching session focused on placement and net recovery.'
),
(
  (SELECT id FROM users WHERE username = 'arav_player'),
  (SELECT id FROM courts WHERE name = 'Banjara Tennis Court'),
  (SELECT id FROM users WHERE username = 'coach_dev'),
  DATE '2026-04-15',
  '06:00',
  '07:00',
  1930.00,
  'Early-morning beginner tennis lesson with serve and forehand basics.'
),
(
  (SELECT id FROM users WHERE username = 'kavya_player'),
  (SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'),
  NULL,
  DATE '2026-04-16',
  '18:00',
  '19:00',
  450.00,
  'Evening court booking for friendly rallies and practice games.'
);

INSERT INTO player_groups (
  name, sport_type, city, skill_level, description, max_members, created_by
) VALUES
(
  'Hyderabad Weekend Smashers',
  'Badminton',
  'Hyderabad',
  'Intermediate',
  'Regular weekend badminton group for rally play and friendly doubles.',
  8,
  (SELECT id FROM users WHERE username = 'ananya_player')
),
(
  'Madhapur Morning Tennis Crew',
  'Tennis',
  'Hyderabad',
  'Beginner',
  'Casual beginner-friendly tennis meetups near Madhapur.',
  6,
  (SELECT id FROM users WHERE username = 'rahul_player')
);

INSERT INTO group_members (group_id, user_id, member_role) VALUES
((SELECT id FROM player_groups WHERE name = 'Hyderabad Weekend Smashers'), (SELECT id FROM users WHERE username = 'ananya_player'), 'captain'),
((SELECT id FROM player_groups WHERE name = 'Madhapur Morning Tennis Crew'), (SELECT id FROM users WHERE username = 'rahul_player'), 'captain'),
((SELECT id FROM player_groups WHERE name = 'Hyderabad Weekend Smashers'), (SELECT id FROM users WHERE username = 'isha_player'), 'member'),
((SELECT id FROM player_groups WHERE name = 'Hyderabad Weekend Smashers'), (SELECT id FROM users WHERE username = 'priya_player'), 'member'),
((SELECT id FROM player_groups WHERE name = 'Madhapur Morning Tennis Crew'), (SELECT id FROM users WHERE username = 'vikram_player'), 'member'),
((SELECT id FROM player_groups WHERE name = 'Hyderabad Weekend Smashers'), (SELECT id FROM users WHERE username = 'neha_player'), 'member'),
((SELECT id FROM player_groups WHERE name = 'Madhapur Morning Tennis Crew'), (SELECT id FROM users WHERE username = 'arav_player'), 'member'),
((SELECT id FROM player_groups WHERE name = 'Hyderabad Weekend Smashers'), (SELECT id FROM users WHERE username = 'kavya_player'), 'member');

INSERT INTO group_messages (group_id, sender_id, message_text) VALUES
(
  (SELECT id FROM player_groups WHERE name = 'Hyderabad Weekend Smashers'),
  (SELECT id FROM users WHERE username = 'ananya_player'),
  'Hi everyone, planning a doubles session this Saturday at 8 AM. Who is in?'
),
(
  (SELECT id FROM player_groups WHERE name = 'Madhapur Morning Tennis Crew'),
  (SELECT id FROM users WHERE username = 'rahul_player'),
  'Welcome to the group. Let us use this chat to coordinate practice sessions.'
);

INSERT INTO reviews (reviewer_id, coach_id, court_id, rating, comment) VALUES
(
  (SELECT id FROM users WHERE username = 'ananya_player'),
  (SELECT id FROM users WHERE username = 'coach_meera'),
  NULL,
  5,
  'Very structured coaching with clear drills and actionable feedback.'
),
(
  (SELECT id FROM users WHERE username = 'rahul_player'),
  (SELECT id FROM users WHERE username = 'coach_arjun'),
  NULL,
  4,
  'Good beginner sessions and patient explanation of fundamentals.'
),
(
  (SELECT id FROM users WHERE username = 'ananya_player'),
  NULL,
  (SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 1'),
  5,
  'Clean court, good lighting, and easy booking experience.'
),
(
  (SELECT id FROM users WHERE username = 'isha_player'),
  (SELECT id FROM users WHERE username = 'coach_saanvi'),
  NULL,
  5,
  'Very encouraging coaching style and easy-to-follow drills for a beginner.'
),
(
  (SELECT id FROM users WHERE username = 'vikram_player'),
  (SELECT id FROM users WHERE username = 'coach_rohan'),
  NULL,
  4,
  'Solid technical cues and well-paced session structure.'
),
(
  (SELECT id FROM users WHERE username = 'priya_player'),
  NULL,
  (SELECT id FROM courts WHERE name = 'Jubilee Hills Shuttle Court 1'),
  5,
  'Great flooring, bright lights, and a premium indoor setup.'
),
(
  (SELECT id FROM users WHERE username = 'neha_player'),
  (SELECT id FROM users WHERE username = 'coach_tara'),
  NULL,
  4,
  'Helpful coaching session with clear feedback and good progression through drills.'
),
(
  (SELECT id FROM users WHERE username = 'arav_player'),
  (SELECT id FROM users WHERE username = 'coach_dev'),
  NULL,
  5,
  'Very patient tennis coach with simple explanations and solid rally practice.'
),
(
  (SELECT id FROM users WHERE username = 'kavya_player'),
  NULL,
  (SELECT id FROM courts WHERE name = 'Gachibowli Smash Arena Court 2'),
  4,
  'Good value court with enough space and a comfortable evening slot.'
);
